trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Azure and image details
  azureSubscription: '<Your-Azure-Subscription>'  # Azure subscription name
  acrName: '<Your-ACR-Name>'                      # Azure Container Registry name
  resourceGroup: '<Your-Resource-Group>'          # resource group
  location: 'EastUS'                              # Azure location

  # Frontend service details
  frontendImageName: 'frontend-app'
  frontendContainerName: 'frontend-container'
  frontendPort: 3000

  # Backend service details
  backendImageName: 'backend-app'
  backendContainerName: 'backend-container'
  backendPort: 5000

stages:
  - stage: BuildAndPush
    displayName: Build and Push Docker Images
    jobs:
      - job: Build
        displayName: Build and Push Frontend and Backend Images
        steps:
          # Step 1: Checkout code
          - task: Checkout@1

          # Step 2: Login to Azure Container Registry
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az acr login --name $(acrName)

          # Step 3: Build and Push Frontend Docker Image
          - task: Docker@2
            inputs:
              command: buildAndPush
              repository: $(acrName).azurecr.io/$(frontendImageName)
              dockerfile: ./frontend/Dockerfile
              tags: latest
              containerRegistry: '$(acrName)'

          # Step 4: Build and Push Backend Docker Image
          - task: Docker@2
            inputs:
              command: buildAndPush
              repository: $(acrName).azurecr.io/$(backendImageName)
              dockerfile: ./backend/Dockerfile
              tags: latest
              containerRegistry: '$(acrName)'

  - stage: Deploy
    displayName: Deploy to Azure Container Instances
    dependsOn: BuildAndPush
    jobs:
      - job: Deploy
        displayName: Deploy Frontend and Backend to ACI
        steps:
          # Step 1: Login to Azure CLI
          - task: AzureCLI@2
            inputs:
              azureSubscription: $(azureSubscription)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                # Deploy Frontend Container
                az container create \
                  --resource-group $(resourceGroup) \
                  --name $(frontendContainerName) \
                  --image $(acrName).azurecr.io/$(frontendImageName):latest \
                  --cpu 1 \
                  --memory 1.5 \
                  --ports $(frontendPort) \
                  --location $(location)

                # Deploy Backend Container
                az container create \
                  --resource-group $(resourceGroup) \
                  --name $(backendContainerName) \
                  --image $(acrName).azurecr.io/$(backendImageName):latest \
                  --cpu 1 \
                  --memory 1.5 \
                  --ports $(backendPort) \
                  --location $(location)
